# Generated by Django 5.2.5 on 2026-10-01 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(blank=True, default='', max_length=64)),
                ('address', models.TextField(blank=True, default='')),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('authorization_text', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IssuerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, default='', max_length=255)),
                ('tax_id', models.CharField(blank=True, default='', max_length=64)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('website', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=128)),
                ('iban', models.CharField(blank=True, default='', max_length=64)),
                ('quote_conditions', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('quote', 'Quote'), ('invoice', 'Invoice')], max_length=16)),
                ('year', models.PositiveIntegerField()),
                ('sequence', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='draft', max_length=16)),
                ('client_snapshot', models.JSONField(blank=True, default=dict)),
                ('layout', models.CharField(choices=[('concept', 'Concept + tax table'), ('numbered', 'Numbered items + summary'), ('invoice', 'Invoice')], default='concept', max_length=16)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('iva_rate', models.DecimalField(decimal_places=2, default=21, max_digits=5)),
                ('irpf_rate', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('totals_style', models.CharField(choices=[('table', 'Table'), ('summary', 'Summary')], default='table', max_length=16)),
                ('authorization_text', models.TextField(blank=True, default='')),
                ('conditions_text', models.TextField(blank=True, default='')),
                ('payment_text', models.TextField(blank=True, default='')),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('irpf_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='billing.client')),
                ('source_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.document')),
            ],
            options={
                'ordering': ['-year', '-sequence'],
                'unique_together': {('kind', 'year', 'sequence')},
            },
        ),
    ]
