# Generated by Django 5.2.5 on 2026-10-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='totals_style',
            field=models.CharField(choices=[('table', 'Table'), ('summary', 'Summary'), ('base', 'Base only')], default='table', max_length=16),
        ),
    ]
