# Generated by Django 5.2.5 on 2025-08-13 19:36

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='projects/'),
        ),
    ]
