# Generated by Django 5.2.5 on 2025-08-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
