# Generated by Django 5.2.5 on 2025-08-13 23:21

import projects.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectimage_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=projects.models.project_image_upload_to),
        ),
    ]
