# Generated by Django 5.2.5 on 2025-08-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
