# Generated by Django 5.2.5 on 2025-08-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_description_project_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content_i18n',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='content_source_lang',
            field=models.CharField(default='es', max_length=8),
        ),
        migrations.AddField(
            model_name='project',
            name='title_i18n',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
