# Generated by Django 5.2.5 on 2025-08-16 10:45

import projects.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_content_i18n_project_content_source_lang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='image_low',
            field=models.ImageField(blank=True, editable=False, null=True, storage=storages.backends.s3.S3Storage(), upload_to=projects.models.project_image_low_upload_to),
        ),
    ]
