# Generated by Django 5.2.5 on 2026-02-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectimage_image_low'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
    ]
