# Generated by Django 5.2.5 on 2026-10-01 13:47

from django.db import migrations, models

# The four disciplines the site launched with, so production starts with the same filters
INITIAL = [
    ('illustration', {'es': 'Ilustración', 'ca': 'Il·lustració', 'en': 'Illustration'}, '#3fcfc6'),
    ('branding', {'es': 'Branding', 'ca': 'Branding', 'en': 'Branding'}, '#bc0e4d'),
    ('campaigns', {'es': 'Campañas', 'ca': 'Campanyes', 'en': 'Campaigns'}, '#e98e47'),
    ('editorial', {'es': 'Editorial y digital', 'ca': 'Editorial i digital', 'en': 'Editorial & Digital'}, '#8265a8'),
]


def seed(apps, schema_editor):
    Category = apps.get_model('projects', 'Category')
    for order, (slug, names, color) in enumerate(INITIAL):
        Category.objects.get_or_create(slug=slug, defaults={'name_i18n': names, 'color': color, 'order': order})


def unseed(apps, schema_editor):
    apps.get_model('projects', 'Category').objects.filter(slug__in=[s for s, _, _ in INITIAL]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_suggested_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name_i18n', models.JSONField(blank=True, default=dict)),
                ('color', models.CharField(default='#bc0e4d', max_length=16)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(seed, unseed),
    ]
