# Generated by Django 5.2.5 on 2026-02-28 20:58

import django.db.models.deletion
import pages.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_about_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=pages.models.about_image_upload_to)),
                ('image_low', models.ImageField(blank=True, editable=False, null=True, storage=storages.backends.s3.S3Storage(), upload_to=pages.models.about_image_low_upload_to)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.about')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
